---
abstract: 'model interface which had more data sources unified, a.k.a data/object mapper'
author:
  - 'Kazuhiro Osawa <yappo <at> shibuya <döt> pl>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Model
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Class::Trigger: 0
  DBD::SQLite: 0
  DBI: 0
  Encode: 0
  Params::Validate: 0
  Storable: 0
resources:
  homepage: http://github.com/yappo/p5-Data-Model/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/yappo/p5-Data-Model.git
version: 0.00007
